// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4ShWaoAFeer7RbtRN3kqQ84NuJQNDnfY',
    appId: '1:1036499757496:web:1ba59983199b9e095fc74d',
    messagingSenderId: '1036499757496',
    projectId: 'projetpcd-2fea3',
    authDomain: 'projetpcd-2fea3.firebaseapp.com',
    storageBucket: 'projetpcd-2fea3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASnDpDyGrgyJkuqiWJQbM3-v0bbNduVjc',
    appId: '1:1036499757496:android:48b27f2d6a3febf95fc74d',
    messagingSenderId: '1036499757496',
    projectId: 'projetpcd-2fea3',
    storageBucket: 'projetpcd-2fea3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb_3xpGUU2_hYwNwZexugYFtLktquyfPw',
    appId: '1:1036499757496:ios:ec7e9146062402c65fc74d',
    messagingSenderId: '1036499757496',
    projectId: 'projetpcd-2fea3',
    storageBucket: 'projetpcd-2fea3.appspot.com',
    iosClientId: '1036499757496-tm6bj8qkrdqhi8u71fpg1pj3125j1osk.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb_3xpGUU2_hYwNwZexugYFtLktquyfPw',
    appId: '1:1036499757496:ios:ec7e9146062402c65fc74d',
    messagingSenderId: '1036499757496',
    projectId: 'projetpcd-2fea3',
    storageBucket: 'projetpcd-2fea3.appspot.com',
    iosClientId: '1036499757496-tm6bj8qkrdqhi8u71fpg1pj3125j1osk.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled1',
  );
}
